name: CI
on: 
  schedule: 
  - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Node.js environment
          uses: actions/setup-node@v4.0.1 
        - name: Install
          run: npm install
        - name: Test
          env:
            BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
            BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          run: npx wdio config/wdio.android.bs.conf.js --spec test/specs/android/delete-note-screen.spec.js
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.3.0
          if: failure()
          with:
            name: logs
            path: logs           
