name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          env:
            BROWSERSTACK_USERNAME: ${{ secrets.BS_KEY }}
            BROWSERSTACK_ACCESS_KEY: ${{ secrets.BS_USER }}
          run: npx wdio config/wdio.android.bs.conf.js --spec test/specs/android/delete-note-screen.spec.js
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs